interface GigabitEthernet0/0
 description WAN_TO_FORTIGATE
 ip address 10.33.1.2 255.255.255.252
 no shutdown
exit

! --- RUTA DE RETORNO (IMPORTANTE PARA EL TRACE) ---
! Esto le dice al ISP cómo llegar a tus redes internas
ip route 192.168.31.0 255.255.255.0 10.33.1.1
ip route 192.168.32.0 255.255.255.0 10.33.1.1

show ip interface brief
show ip route
